#!/usr/bin/env python3
"""Migrate verbose TryGetProperty + ValueKind checks to HandlerBase.TryGet* helpers.

Patterns handled (the common cases — edge variants are left alone):

  # Float single-line assignment:
  if ( args.TryGetProperty( "X", out var xEl ) && xEl.ValueKind == JsonValueKind.Number )
      target = xEl.GetSingle();
  -->
  if ( HandlerBase.TryGetFloat( args, "X", out var x ) ) target = x;

  # Int single-line assignment (GetInt32):
  if ( args.TryGetProperty( "X", out var xEl ) && xEl.ValueKind == JsonValueKind.Number )
      target = xEl.GetInt32();
  -->
  if ( HandlerBase.TryGetInt( args, "X", out var x ) ) target = x;

  # Bool multi-line (the standard True||False check):
  if ( args.TryGetProperty( "X", out var xEl ) &&
       ( xEl.ValueKind == JsonValueKind.True || xEl.ValueKind == JsonValueKind.False ) )
      target = xEl.GetBoolean();
  -->
  if ( HandlerBase.TryGetBool( args, "X", out var x ) ) target = x;

The helper-var name is generated by stripping the trailing 'El' suffix.
Targets can be any expression (`obj.Prop`, `fg.Color`, `wp.PanelSize.X`, etc.).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Common core pattern:
# (indent)if ( args.TryGetProperty( "name", out var PREFIX_El ) ...
#
# The target (LHS of assignment) is any non-whitespace up to '='; we capture it
# lazily so we stop at the first ' = '.

# Float — assignment is obj.prop = xEl.GetSingle();
FLOAT_PATTERN = re.compile(
    r"(?P<indent>[ \t]+)"
    r"if\s*\(\s*args\.TryGetProperty\(\s*\"(?P<key>[A-Za-z_][\w]*)\"\s*,\s*out\s+var\s+(?P<var>[A-Za-z_][\w]*)El\s*\)\s*"
    r"&&\s*(?P=var)El\.ValueKind\s*==\s*JsonValueKind\.Number\s*\)\r?\n"
    r"(?P=indent)[ \t]+(?P<target>[^\n=]+?)\s*=\s*(?P=var)El\.GetSingle\(\s*\)\s*;",
    re.MULTILINE,
)

# Int — identical shape but assignment uses .GetInt32()
INT_PATTERN = re.compile(
    r"(?P<indent>[ \t]+)"
    r"if\s*\(\s*args\.TryGetProperty\(\s*\"(?P<key>[A-Za-z_][\w]*)\"\s*,\s*out\s+var\s+(?P<var>[A-Za-z_][\w]*)El\s*\)\s*"
    r"&&\s*(?P=var)El\.ValueKind\s*==\s*JsonValueKind\.Number\s*\)\r?\n"
    r"(?P=indent)[ \t]+(?P<target>[^\n=]+?)\s*=\s*(?P=var)El\.GetInt32\(\s*\)\s*;",
    re.MULTILINE,
)

# Bool multi-line — the True||False guard split across two lines
BOOL_PATTERN_MULTILINE = re.compile(
    r"(?P<indent>[ \t]+)"
    r"if\s*\(\s*args\.TryGetProperty\(\s*\"(?P<key>[A-Za-z_][\w]*)\"\s*,\s*out\s+var\s+(?P<var>[A-Za-z_][\w]*)El\s*\)\s*&&\r?\n"
    r"(?P=indent)[ \t]+\(\s*(?P=var)El\.ValueKind\s*==\s*JsonValueKind\.True\s*\|\|\s*(?P=var)El\.ValueKind\s*==\s*JsonValueKind\.False\s*\)\s*\)\r?\n"
    r"(?P=indent)[ \t]+(?P<target>[^\n=]+?)\s*=\s*(?P=var)El\.GetBoolean\(\s*\)\s*;",
    re.MULTILINE,
)

# Bool single-line variant where guard is on one line
BOOL_PATTERN_SINGLELINE = re.compile(
    r"(?P<indent>[ \t]+)"
    r"if\s*\(\s*args\.TryGetProperty\(\s*\"(?P<key>[A-Za-z_][\w]*)\"\s*,\s*out\s+var\s+(?P<var>[A-Za-z_][\w]*)El\s*\)\s*"
    r"&&\s*\(\s*(?P=var)El\.ValueKind\s*==\s*JsonValueKind\.True\s*\|\|\s*(?P=var)El\.ValueKind\s*==\s*JsonValueKind\.False\s*\)\s*\)\r?\n"
    r"(?P=indent)[ \t]+(?P<target>[^\n=]+?)\s*=\s*(?P=var)El\.GetBoolean\(\s*\)\s*;",
    re.MULTILINE,
)


def _subst(kind: str):
    def repl(m: re.Match) -> str:
        indent = m.group("indent")
        key = m.group("key")
        var = m.group("var")
        target = m.group("target").rstrip()
        return f'{indent}if ( HandlerBase.TryGet{kind}( args, "{key}", out var {var} ) ) {target} = {var};'
    return repl


def process(content: str) -> tuple[str, dict[str, int]]:
    counts = {"float": 0, "int": 0, "bool_ml": 0, "bool_sl": 0}

    new, n = FLOAT_PATTERN.subn(_subst("Float"), content)
    counts["float"] = n

    new, n = INT_PATTERN.subn(_subst("Int"), new)
    counts["int"] = n

    new, n = BOOL_PATTERN_MULTILINE.subn(_subst("Bool"), new)
    counts["bool_ml"] = n

    new, n = BOOL_PATTERN_SINGLELINE.subn(_subst("Bool"), new)
    counts["bool_sl"] = n

    return new, counts


def discover(root: Path) -> list[Path]:
    return sorted((root / "editor").rglob("*.cs"))


def main() -> int:
    base = Path(__file__).resolve().parent.parent
    grand = {"float": 0, "int": 0, "bool_ml": 0, "bool_sl": 0}
    for path in discover(base):
        original = path.read_text(encoding="utf-8")
        new, counts = process(original)
        total = sum(counts.values())
        if total:
            path.write_text(new, encoding="utf-8")
            rel = path.relative_to(base).as_posix()
            bits = ", ".join(f"{k}={v}" for k, v in counts.items() if v)
            print(f"  {rel}: {total}  ({bits})")
            for k, v in counts.items():
                grand[k] += v
    print(f"\nTotal: float={grand['float']}, int={grand['int']}, "
          f"bool_ml={grand['bool_ml']}, bool_sl={grand['bool_sl']} "
          f"— {sum(grand.values())} sites migrated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
